/**
 * Integration tests for scan.service — ordered validation gates against the
 * form_qr_test database.
 *
 * Tests cover:
 *  - Unauthenticated-ish request (non-Empleado role → 403)
 *  - No active branch → 403
 *  - Active branch but questionnaire not assigned → 403
 *  - Assigned + published version → 200 with questions
 *  - No published version → 422
 *
 * Requirements: form_qr_test DB must be running with migrations applied.
 * Run with: pnpm test --project integration
 */
import { describe, expect, it, beforeEach } from 'vitest'
import { prisma } from '@/lib/db'
import { resolveScan } from './scan.service'
import type { Principal } from '@/lib/types'
import { RESPONSE_STATUS } from '@/lib/types'

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeEmpleadoPrincipal(userId: string): Principal {
  return { userId, role: 'Empleado', passwordChangeRequired: false }
}

function makeAdminPrincipal(userId: string): Principal {
  return { userId, role: 'Administrador', passwordChangeRequired: false }
}

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

let empleadoId: string
let branchId: string
let questionnaireId: string
let qrToken: string

beforeEach(async () => {
  await prisma.$executeRawUnsafe(
    'TRUNCATE TABLE "QuestionnaireBranch", "Question", "QuestionnaireVersion", "Questionnaire", "BranchAssignment", "Branch", "RefreshToken", "User", "AuditLog" RESTART IDENTITY CASCADE'
  )

  // Create a user with role Empleado
  const user = await prisma.user.create({
    data: {
      nombres: 'Test',
      apellidos: 'Empleado',
      cedula: '11111111',
      passwordHash: 'hash',
      role: 'Empleado',
      passwordChangeRequired: false,
    },
  })
  empleadoId = user.id

  // Create a branch
  const branch = await prisma.branch.create({ data: { name: 'Test Branch' } })
  branchId = branch.id

  // Create a questionnaire — qrToken is auto-generated by @default(cuid()) at DB level
  const q = await prisma.questionnaire.create({
    data: { title: 'Scan Test Questionnaire' },
  })
  questionnaireId = q.id
  qrToken = q.qrToken
})

// ---------------------------------------------------------------------------
// Gate 1: non-Empleado role → 403
// ---------------------------------------------------------------------------

describe('scan.service integration — gate 1: Empleado-only', () => {
  it('Administrador principal → throws 403', async () => {
    const admin = makeAdminPrincipal('admin_01')
    await expect(resolveScan(admin, qrToken)).rejects.toMatchObject({
      statusCode: 403,
      message: 'insufficient_permissions',
    })
  })
})

// ---------------------------------------------------------------------------
// Gate 2: unknown qrToken → 404
// ---------------------------------------------------------------------------

describe('scan.service integration — gate 2: unknown qrToken', () => {
  it('completely unknown token → throws 404', async () => {
    const principal = makeEmpleadoPrincipal(empleadoId)
    await expect(resolveScan(principal, 'nonexistent-token')).rejects.toMatchObject({
      statusCode: 404,
      message: 'questionnaire_not_found',
    })
  })
})

// ---------------------------------------------------------------------------
// Gate 3a: no active branch → 403
// ---------------------------------------------------------------------------

describe('scan.service integration — gate 3a: no active branch', () => {
  it('employee with no BranchAssignment → throws 403 no_active_branch', async () => {
    const principal = makeEmpleadoPrincipal(empleadoId)
    await expect(resolveScan(principal, qrToken)).rejects.toMatchObject({
      statusCode: 403,
      message: 'no_active_branch',
    })
  })
})

// ---------------------------------------------------------------------------
// Gate 3b: branch exists but questionnaire not assigned → 403
// ---------------------------------------------------------------------------

describe('scan.service integration — gate 3b: questionnaire not assigned to branch', () => {
  it('employee has active branch but questionnaire not assigned → throws 403', async () => {
    // Give the employee an active branch assignment
    await prisma.branchAssignment.create({
      data: { userId: empleadoId, branchId, assignedAt: new Date() },
    })
    // Do NOT assign the questionnaire to the branch

    const principal = makeEmpleadoPrincipal(empleadoId)
    await expect(resolveScan(principal, qrToken)).rejects.toMatchObject({
      statusCode: 403,
      message: 'questionnaire_not_assigned',
    })
  })
})

// ---------------------------------------------------------------------------
// Gate 4: questionnaire assigned but no published version → 422
// ---------------------------------------------------------------------------

describe('scan.service integration — gate 4: no published version', () => {
  it('questionnaire assigned but currentVersionId is null → throws 422', async () => {
    // Give the employee an active branch and assign the questionnaire
    await prisma.branchAssignment.create({
      data: { userId: empleadoId, branchId, assignedAt: new Date() },
    })
    await prisma.questionnaireBranch.create({
      data: { questionnaireId, branchId },
    })
    // Do NOT publish any version (currentVersionId remains null)

    const principal = makeEmpleadoPrincipal(empleadoId)
    await expect(resolveScan(principal, qrToken)).rejects.toMatchObject({
      statusCode: 422,
      message: 'no_published_version',
    })
  })
})

// ---------------------------------------------------------------------------
// Happy path: assigned + published version → 200 with questions
// ---------------------------------------------------------------------------

describe('scan.service integration — happy path: assigned + published version', () => {
  it('valid scan → returns ScanResolutionDTO with questions and status:absent', async () => {
    // Setup: employee → branch → assignment
    await prisma.branchAssignment.create({
      data: { userId: empleadoId, branchId, assignedAt: new Date() },
    })
    await prisma.questionnaireBranch.create({
      data: { questionnaireId, branchId },
    })

    // Create and publish a version
    const version = await prisma.questionnaireVersion.create({
      data: {
        questionnaireId,
        versionNumber: 1,
        status: 'published',
        publishedAt: new Date(),
      },
    })
    await prisma.questionnaire.update({
      where: { id: questionnaireId },
      data: { currentVersionId: version.id },
    })

    // Add a question to the version
    const question = await prisma.question.create({
      data: {
        versionId: version.id,
        order: 1,
        type: 'boolean',
        prompt: 'Did you complete the daily checklist?',
        required: true,
        config: {},
      },
    })

    const principal = makeEmpleadoPrincipal(empleadoId)
    const result = await resolveScan(principal, qrToken)

    expect(result.questionnaireId).toBe(questionnaireId)
    expect(result.status).toBe(RESPONSE_STATUS.ABSENT)
    expect(result.response).toBeNull()
    expect(result.version.id).toBe(version.id)
    expect(result.version.status).toBe('published')
    expect(result.questions).toHaveLength(1)
    expect(result.questions[0].id).toBe(question.id)
    expect(result.questions[0].type).toBe('boolean')
    expect(result.questions[0].order).toBe(1)
  })

  it('valid scan with multiple questions returns them ordered', async () => {
    await prisma.branchAssignment.create({
      data: { userId: empleadoId, branchId, assignedAt: new Date() },
    })
    await prisma.questionnaireBranch.create({
      data: { questionnaireId, branchId },
    })

    const version = await prisma.questionnaireVersion.create({
      data: {
        questionnaireId,
        versionNumber: 1,
        status: 'published',
        publishedAt: new Date(),
      },
    })
    await prisma.questionnaire.update({
      where: { id: questionnaireId },
      data: { currentVersionId: version.id },
    })

    // Insert in reverse order to test the ordering
    await prisma.question.create({
      data: { versionId: version.id, order: 3, type: 'short_text', prompt: 'Q3', required: false, config: {} },
    })
    await prisma.question.create({
      data: { versionId: version.id, order: 1, type: 'boolean', prompt: 'Q1', required: true, config: {} },
    })
    await prisma.question.create({
      data: { versionId: version.id, order: 2, type: 'scale', prompt: 'Q2', required: false, config: { min: 1, max: 5 } },
    })

    const principal = makeEmpleadoPrincipal(empleadoId)
    const result = await resolveScan(principal, qrToken)

    expect(result.questions).toHaveLength(3)
    expect(result.questions.map((q) => q.order)).toEqual([1, 2, 3])
  })
})

// ---------------------------------------------------------------------------
// qrToken stability — soft-deleted questionnaire → 404
// ---------------------------------------------------------------------------

describe('scan.service integration — soft-deleted questionnaire', () => {
  it('soft-deleted questionnaire is not found by qrToken → 404', async () => {
    await prisma.questionnaire.update({
      where: { id: questionnaireId },
      data: { deletedAt: new Date() },
    })

    const principal = makeEmpleadoPrincipal(empleadoId)
    await expect(resolveScan(principal, qrToken)).rejects.toMatchObject({
      statusCode: 404,
      message: 'questionnaire_not_found',
    })
  })
})
